spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: recipe_realm
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_realm?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true

spring-doc:
  api-docs:
    path: /api-docs

secret-key: 432A462D4A614E645267556B58703273357638792F423F4528472B4B62506553